name: Install Monorepo
description: A GitHub Action to install the monorepo

runs:
  using: 'composite'
  steps:
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          cache: 'pnpm'
      - name: Install
        shell: bash
        run: pnpm i