packages:
  - packages/*
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
catalogs:
  eslint:
    eslint: ^9
    "@eslint/eslintrc": ^3
    "@eslint/js": ^9

  react:
    react: ^19
    react-dom: ^19
    "@types/react": ^19
    "@types/react-dom": ^19
    eslint-config-react: ^1
    eslint-plugin-react: ^7
    "@testing-library/react": ^16

  # Must be kept in sync with each other!
  nx:
    nx: 21.5.3
    "@nx/eslint": "21.5.3"
    "@nx/next": "21.5.3"
