name: CD - Build and Publish Docker Image

on:
    push:
        branches:
            - main
        tags:
            - '*.*.*'
    
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Get metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: moriryuuji3/next-web-app
                  tags: |
                      type=edge,branch=main
                      type=semver,pattern={{version}}
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                    username: ${{ vars.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  file: ./packages/next-web-app/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

