name: CD - Tag Releases

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    tag-release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          actions: read
        steps:
            # Using our CI/CD bot so we can bypass branch restrictions
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ vars.CI_CD_BOT_APP_ID }}
                private-key: ${{ secrets.CI_CD_BOT_PRIVATE_KEY }}
            - uses: actions/checkout@v5
            - name: Install monorepo
              uses: ./.github/actions/install-monorepo
              with:
                branch: ${{ github.event.base_ref }}
                git_token: ${{ steps.app-token.outputs.token }}
            - name: Set author
              run: |
                git config user.email "mori.ryuuji3@gmail.com"
                git config user.name "Josh Lalonde"
            - name: Tag Release
              run: |
                pnpm nx release --skip-publish
            - name: Push tags
              run: |
                git push
                git push --tags