name: CD - Tag Releases

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    tag-release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          actions: read
        steps:
            # Using our CI/CD bot so we can bypass branch restrictions
            - uses: peter-murray/workflow-application-token-action@v3
              id: app-token
              with:
                application_id: ${{ vars.CI_CD_BOT_APP_ID }}
                application_private_key: ${{ secrets.CI_CD_BOT_PRIVATE_KEY }}
            - uses: actions/checkout@v5
              with:
                token: ${{ steps.app-token.outputs.token }}
            - name: Install monorepo
              uses: ./.github/actions/install-monorepo
              with:
                branch: ${{ github.event.base_ref }}
                git_token: ${{ steps.app-token.outputs.token }}
            - name: Tag Release
              run: |
                git config user.email "mori.ryuuji3@gmail.com"
                git config user.name "Josh Lalonde"
                pnpm nx release --skip-publish
                git push
                git push --tags