name: CD - Tag Releases

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    tag-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  # Use a PAT to trigger the CD workflows
                  token: ${{ secrets.GIT_TOKEN }}
            - name: Set author
              run: |
                git config user.email "mori.ryuuji3@gmail.com"
                git config user.name "Josh Lalonde"
                  
            - name: Install monorepo
              uses: ./.github/actions/install-monorepo
              with:
                branch: ${{ github.event.base_ref }}
            - name: Tag Release
              run: |
                pnpm nx release --skip-publish