name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            # TODO: will need to prevent re-running tests if the event type is only edited
            - edited
        branches:
            - main

# Prevent concurrent runs on consecutive commits
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
    cancel-in-progress: true

jobs:
    determine-which-tests-to-check:
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.determine-affected-packages.outputs.affected_packages }}
        steps:
          - uses: actions/checkout@v5
          - name: Determine affected packages
            id: determine-affected-packages
            uses: ./.github/actions/determine-affected-packages
            with:
              branch: ${{ github.head_ref }}
              since_ref: origin/${{ github.base_ref }}

    run-tests:
        needs: determine-which-tests-to-check
        runs-on: ubuntu-latest
        strategy:
          matrix:
            package: ${{ fromJson(needs.determine-which-tests-to-check.outputs.packages) }}
        steps:
          - uses: actions/checkout@v5
          - name: Install monorepo
            uses: ./.github/actions/install-monorepo
            with:
              branch: ${{ github.head_ref }}
          - name: Run tests
            run: |
              pnpm --filter ${{ matrix.package.name }} --if-present test

    verify-pr-title:
        name: Verify PR Title
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/install-monorepo
              with:
                branch: ${{ github.head_ref }}
            - name: Check PR title
              env:
                PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                echo $PR_TITLE | pnpm commitlint
              


    ci-passed:
        name: CI Passed
        if: always()
        needs:
            - verify-pr-title
            - run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Assert that all jobs are green
              uses: re-actors/alls-green@release/v1
              with:
                jobs: ${{ toJSON(needs) }}
