name: CI - Verify Code

on:
    pull_request:
        branches:
            - main

# Prevent concurrent runs on consecutive commits
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
    cancel-in-progress: true

jobs:
    determine-which-tests-to-check:
        name: Determine which tests to check
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.determine-affected-packages.outputs.affected_packages }}
        steps:
          - uses: actions/checkout@v5
          - name: Determine affected packages
            id: determine-affected-packages
            uses: ./.github/actions/determine-affected-packages
            with:
              branch: ${{ github.head_ref }}
              since_ref: origin/${{ github.base_ref }}

    run-tests:
        needs: determine-which-tests-to-check
        if: ${{ needs.determine-which-tests-to-check.outputs.packages != '[]' }}
        runs-on: ubuntu-latest
        strategy:
          matrix:
            package: ${{ fromJson(needs.determine-which-tests-to-check.outputs.packages) }}
        name: Run tests (${{ matrix.package.package }})
        steps:
          - uses: actions/checkout@v5
            with:
              fetch-depth: 0
              ref: ${{ github.head_ref }}
          - name: Install monorepo
            uses: ./.github/actions/install-monorepo
          - name: Run tests
            run: |
              pnpm --filter ${{ matrix.package.package }} --if-present test

    ci-passed:
        name: CI Passed
        if: always()
        needs:
            - run-tests
        runs-on: ubuntu-latest
        steps:
            - name: Get skips
              id: get-skips
              env:
                  NEEDS: ${{ toJson(needs) }}
              run: |
                  # Produce a comma-delimited list from any skipped jobs
                  # Assumption: any skipped workflow was skipped intentionally
                  skipped_jobs=$(echo $NEEDS | jq -r 'to_entries | map(select(.value.result == "skipped")) | map(.key) | join(",")')

                  # debugging output
                  echo "skipped_jobs=$skipped_jobs"
                  echo "skipped_jobs=$skipped_jobs" >> $GITHUB_OUTPUT
            - name: Assert that all jobs are green
              uses: re-actors/alls-green@release/v1
              with:
                jobs: ${{ toJSON(needs) }}
                allowed-skips: ${{ steps.get-skips.outputs.skipped_jobs }}
